const polyatomic = [
    {
        "name":"Acetate",
        "formula":"C<sub>2</sub>H<sub>3</sub>O<sub>2</sub><sup>-</sup>",
        "formula_simple":"C2H3O2",
        "charge":-1
    },
    {
        "name":"Hydrogen Carbonate",
        "formula":"HCO<sub>3</sub><sup>-</sup>",
        "formula_simple":"HCO3",
        "charge":-1
    },
    {
        "name":"Nitrite",
        "formula":"NO<sub>2</sub><sup>-</sup>",
        "formula_simple":"NO2",
        "charge":-1
    },   
    {
        "name":"Nitrate",
        "formula":"NO<sub>3</sub><sup>-</sup>",
        "formula_simple":"NO3",
        "charge":-1
    },
    {
        "name":"Cyanide",
        "formula":"CN<sup>-</sup>",
        "formula_simple":"CN",
        "charge":-1
    },
    {
        "name":"Hydroxide",
        "formula":"OH<sup>-</sup>",
        "formula_simple":"OH",
        "charge":-1
    },
 
    {
        "name":"Permanganate",
        "formula":"MnO<sub>4</sub><sup>-</sup>",
        "formula_simple":"MNO4",
        "charge":-1
    },
    {
        "name":"Hypochlorite",
        "formula":"ClO<sup>-</sup>",
        "formula_simple":"CLO",
        "charge":-1
    },
    {
        "name":"Chlorite",
        "formula":"ClO<sub>2</sub><sup>-</sup>",
        "formula_simple":"ClO2",
        "charge":-1
    },
    {
        "name":"Chlorate",
        "formula":"ClO<sub>3</sub><sup>-</sup>",
        "formula_simple":"CLO3",
        "charge":-1
    },
    {
        "name":"Perchlorate",
        "formula":"ClO<sub>4</sub><sup>-</sup>",
        "formula_simple":"CLO4",
        "charge":-1
    },
    {
        "name":"Sulfite",
        "formula":"SO<sub>3</sub><sup>2-</sup>",
        "formula_simple":"SO3",
        "charge":-2
    },
    {
        "name":"Sulfate",
        "formula":"SO<sub>4</sub><sup>2-</sup>",
        "formula_simple":"SO4",
        "charge":-2
    },
    {
        "name":"Carbonate",
        "formula":"CO<sub>3</sub><sup>2-</sup>",
        "formula_simple":"CO3",
        "charge":-2
    },
    {
        "name":"Chromate",
        "formula":"CrO<sub>4</sub><sup>2-</sup>",
        "formula_simple":"CRO4",
        "charge":-2
    },
    {
        "name":"Dichromate",
        "formula":"Cr<sub>2</sub>O<sub>7</sub><sup>2-</sup>",
        "formula_simple":"CR2O7",
        "charge":-2
    },
    {
        "name":"Peroxide",
        "formula":"O<sub>2</sub><sup>2-</sup>",
        "formula_simple":"O2",
        "charge":-2
    },
    {
        "name":"Phosphite",
        "formula":"PO<sub>3</sub><sup>3-</sup>",
        "formula_simple":"PO3",
        "charge":-3
    },
    {
        "name":"Phosphate",
        "formula":"PO<sub>4</sub><sup>3-</sup>",
        "formula_simple":"PO4",
        "charge":-3
    },
    {
        "name":"Ammonium",
        "formula":"NH<sub>4</sub><sup>+</sup>",
        "formula_simple":"NH4",
        "charge":1
    },
    {
        "name":"Hydronium",
        "formula":"H<sub>3</sub>O<sup>+</sup>",
        "formula_simple":"H3O",
        "charge":1
    },

]